[deploy]
bucket = 'cfn-artifacts-d'
region = 'eu-south-1'
stack_name = 'CrdService'



#        - Key: 'routing.http2.enabled'
#          Value: 'true'
#        - Key: 'routing.http.preserve_host_header.enabled'
#          Value: 'true'
#        - Key: 'deletion_protection.enabled'
#          Value: 'true'
#        - Key: 'load_balancing.cross_zone.enabled'
#          Value: 'true'
#        - Key: 'access_logs.s3.enabled'
#          Value: 'false'