name: Build and Deploy Static Website to S3

on:
  push:
    branches:
      - prod
    paths:
      - "frontend-react-js/**"  # Trigger only when files in this folder change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Adjust based on your project

      - name: Install Dependencies
        run: |
          cd frontend-react-js
          npm install

      - name: Disable CI checks
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Build the Website
        env:
          REACT_APP_BACKEND_URL: "https://api.denisgulev.com"
          REACT_APP_FRONTEND_URL: "http://cruddur.denisgulev.com"
          REACT_APP_AWS_PROJECT_REGION: ${{ secrets.AWS_REGION }}
          REACT_APP_AWS_COGNITO_REGION: ${{ secrets.AWS_REGION }}
          REACT_APP_AWS_USER_POOLS_ID: ${{ secrets.AWS_USER_POOL_ID }}
          REACT_APP_CLIENT_ID: ${{ secrets.AWS_USER_POOL_APP_CLIENT_ID }}
          REACT_APP_API_GATEWAY_ENDPOINT_URL: ${{ secrets.API_GATEWAY_ENDPOINT_URL }}
        run: |
          cd frontend-react-js
          npm run build

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync frontend-react-js/build/ s3://${{ secrets.S3_BUCKET_NAME }}/ --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DIST_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Delete Build Folder
        run: rm -rf frontend-react-js/build